export $(shell sed 's/=.*//' .Xmodmap)

switch-to-rexusm84pro:
	bash .switchkeyboardprofile.sh .Xmodmap.rexusm84pro .Xmodmap
switch-to-asusdefaultcustom:
	bash .switchkeyboardprofile.sh .Xmodmap.backup .Xmodmap 